# Meta Data for SEO

## Homepage
title = "Guide Oz"
titleSeparator = "-"
titleAddition = "Guide collaboratif"
description = "Ressource pedagogique collaborative pour le langage de programmation multiparadigme Oz."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "henkverlinde"
twitterCreator = "henkverlinde"
facebookAuthor = "verlinde.henk"
facebookPublisher = "verlinde.henk"
ogLocale = "fr_be"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Propulse par <a href=\"https://gohugo.io/\">Hugo</a>, et <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = true
alertText = "Vous aimez ce guide? <a class=\"alert-link\" href=\"https://github.com/Ahzed11/guide-collaboratif-oz\">Ajoutez une etoile sur GitHub</a>. Merci!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
